import { StyleSheet } from "react-native"

export default StyleSheet.create({
    container:{
        flexGrow:1,
        justifyContent:'center',
        alignItems:'center',
        padding:20,
        backgroundColor:'#f0f2f5'
    },
    card:{
        backgroundColor:'#fff',
        borderRadius:16,
        width:'100%',
        maxWidth:500,
        padding:30,
    },
    title:{
        fontSize:20,
        fontWeight:'bold',
        color:'#333',
        marginBottom:20,
        textAlign:'center'
    },
    textInput:{
        borderWidth:1,
        borderColor:'#ccc',
        marginBottom:15,
        paddingHorizontal:20,
        paddingVertical:16,
        borderRadius:8,
        backgroundColor:'#fff',
        fontSize:16,
        color:'#333'
    },
    addBtn:{
        marginTop:10,
        borderRadius:10,
        alignItems:'center',
        backgroundColor:'#4CAF50',
        paddingVertical:14,
    },
    btnTxt:{
        fontSize:18,
        color:'#fff'
    },
    errorTxt:{
        color:'#DD0303',
        fontSize:12,
        textAlign:'center',
        marginBottom:8,
  }
});